using MediatR;
using WalletTransfer.Domain;

namespace WalletTransfer.Application;

public sealed record CreateTransferCommand(string SourceWalletId,string DestinationWalletId,string SourceProvider,string DestinationProvider,decimal Amount,string Currency,string ClientIdempotencyKey) : IRequest<Guid>;
public sealed record GetTransferByIdQuery(Guid TransferId) : IRequest<Transfer?>;
public sealed record TransferRequested(Guid TransferId): INotification; public sealed record RequestValidated(Guid TransferId): INotification; public sealed record WalletsValidated(Guid TransferId): INotification; public sealed record RulesChecked(Guid TransferId): INotification; public sealed record BalanceChecked(Guid TransferId): INotification; public sealed record AmountBlocked(Guid TransferId,string BlockReferenceId): INotification; public sealed record MoneyTransferred(Guid TransferId,string TransferReferenceId): INotification; public sealed record TransferFinalized(Guid TransferId): INotification; public sealed record TransferCompleted(Guid TransferId): INotification; public sealed record TransferStepRetryRequested(Guid TransferId, TransferStep Step): INotification;

public interface ITransferRepository { Task<Transfer?> GetByIdAsync(Guid id, CancellationToken ct); Task<Transfer?> GetByClientKeyAsync(string key, CancellationToken ct); Task AddAsync(Transfer transfer, CancellationToken ct); Task<List<Transfer>> GetDueRetriesAsync(DateTimeOffset now, CancellationToken ct); }
public interface IOutboxRepository { Task AddAsync(object @event, CancellationToken ct); Task<List<OutboxMessage>> GetPendingAsync(int take, CancellationToken ct); }
public interface IUnitOfWork { Task<int> SaveChangesAsync(CancellationToken ct); }
public interface IClock { DateTimeOffset UtcNow { get; } }
public interface IWalletProviderResolver { IWalletProvider Resolve(string providerName); }
public interface IWalletProvider { string ProviderName { get; } Task<WalletValidationResult> ValidateWalletAsync(string walletId,string currency,CancellationToken ct); Task<BalanceResult> GetBalanceAsync(string walletId,string currency,CancellationToken ct); Task<BlockResult> BlockAsync(BlockMoneyRequest request,CancellationToken ct); Task<TransferResult> TransferAsync(TransferMoneyRequest request,CancellationToken ct); Task<UnblockResult> UnblockAsync(UnblockMoneyRequest request,CancellationToken ct); Task<ProviderTransferStatusResult> GetTransferStatusAsync(string idempotencyKey,CancellationToken ct); }
public record WalletValidationResult(bool Success,string? ErrorCode=null,bool Retryable=false); public record BalanceResult(bool Success,decimal Available,string? ErrorCode=null,bool Retryable=false); public record BlockResult(bool Success,string? BlockReferenceId,string? ErrorCode=null,bool Retryable=false); public record TransferResult(bool Success,string? TransferReferenceId,string? ErrorCode=null,bool Retryable=false); public record UnblockResult(bool Success,string? ErrorCode=null,bool Retryable=false); public record ProviderTransferStatusResult(string Status);
public record BlockMoneyRequest(string WalletId,decimal Amount,string Currency,string IdempotencyKey); public record TransferMoneyRequest(string SourceWalletId,string DestinationWalletId,decimal Amount,string Currency,string IdempotencyKey); public record UnblockMoneyRequest(string WalletId,string BlockReferenceId,string IdempotencyKey);
public sealed record OutboxMessage(Guid Id,string Type,string Payload,DateTimeOffset OccurredAt,DateTimeOffset? ProcessedAt,int RetryCount,string? Error,string Status);

public class CreateTransferHandler(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow,IClock clock): IRequestHandler<CreateTransferCommand,Guid>
{ public async Task<Guid> Handle(CreateTransferCommand c, CancellationToken ct){ var existing=await repo.GetByClientKeyAsync(c.ClientIdempotencyKey,ct); if(existing is not null) return existing.Id; var t=Transfer.Create(Guid.NewGuid(),c.SourceWalletId,c.DestinationWalletId,c.SourceProvider,c.DestinationProvider,c.Amount,c.Currency,c.ClientIdempotencyKey,clock.UtcNow); await repo.AddAsync(t,ct); await outbox.AddAsync(new TransferRequested(t.Id),ct); await uow.SaveChangesAsync(ct); return t.Id; } }
public class GetTransferHandler(ITransferRepository repo): IRequestHandler<GetTransferByIdQuery,Transfer?>{public Task<Transfer?> Handle(GetTransferByIdQuery q,CancellationToken ct)=>repo.GetByIdAsync(q.TransferId,ct);} 
public static class ApplicationDi { public static IServiceCollection AddApplication(this IServiceCollection services){ services.AddMediatR(cfg=>cfg.RegisterServicesFromAssembly(typeof(ApplicationDi).Assembly)); services.AddScoped<INotificationHandler<TransferRequested>, TransferRequestedHandler>(); services.AddScoped<INotificationHandler<RequestValidated>, RequestValidatedHandler>(); services.AddScoped<INotificationHandler<WalletsValidated>, WalletsValidatedHandler>(); services.AddScoped<INotificationHandler<RulesChecked>, RulesCheckedHandler>(); services.AddScoped<INotificationHandler<BalanceChecked>, BalanceCheckedHandler>(); services.AddScoped<INotificationHandler<AmountBlocked>, AmountBlockedHandler>(); services.AddScoped<INotificationHandler<MoneyTransferred>, MoneyTransferredHandler>(); return services; } }

public abstract class StepHandlerBase(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow){ protected async Task<Transfer?> Load(Guid id,CancellationToken ct)=>await repo.GetByIdAsync(id,ct); protected async Task Next(object e,CancellationToken ct){ await outbox.AddAsync(e,ct); await uow.SaveChangesAsync(ct);} }
public sealed class TransferRequestedHandler(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow): StepHandlerBase(repo,outbox,uow), INotificationHandler<TransferRequested>{ public async Task Handle(TransferRequested n, CancellationToken ct){ var t=await Load(n.TransferId,ct); if(t is null||t.IsStepCompleted(TransferStep.RequestValidation)) return; t.MarkRequestValidated(); await Next(new RequestValidated(t.Id),ct);} }
public sealed class RequestValidatedHandler(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow,IWalletProviderResolver r): StepHandlerBase(repo,outbox,uow), INotificationHandler<RequestValidated>{ public async Task Handle(RequestValidated n, CancellationToken ct){ var t=await Load(n.TransferId,ct); if(t is null||t.IsStepCompleted(TransferStep.WalletValidation)) return; var s=await r.Resolve(t.SourceProvider).ValidateWalletAsync(t.SourceWalletId,t.Currency,ct); var d=await r.Resolve(t.DestinationProvider).ValidateWalletAsync(t.DestinationWalletId,t.Currency,ct); if(!s.Success||!d.Success){ t.MarkPermanentFailure(TransferStep.WalletValidation,s.ErrorCode??d.ErrorCode??"INVALID_WALLET"); await uow.SaveChangesAsync(ct); return;} t.MarkWalletsValidated(); await Next(new WalletsValidated(t.Id),ct);} }
public sealed class WalletsValidatedHandler(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow): StepHandlerBase(repo,outbox,uow), INotificationHandler<WalletsValidated>{ public async Task Handle(WalletsValidated n,CancellationToken ct){ var t=await Load(n.TransferId,ct); if(t is null||t.IsStepCompleted(TransferStep.RuleCheck)) return; t.MarkRulesChecked(); await Next(new RulesChecked(t.Id),ct);} }
public sealed class RulesCheckedHandler(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow,IWalletProviderResolver resolver): StepHandlerBase(repo,outbox,uow), INotificationHandler<RulesChecked>{ public async Task Handle(RulesChecked n,CancellationToken ct){ var t=await Load(n.TransferId,ct); if(t is null||t.IsStepCompleted(TransferStep.BalanceCheck)) return; var b=await resolver.Resolve(t.SourceProvider).GetBalanceAsync(t.SourceWalletId,t.Currency,ct); if(!b.Success||b.Available<t.Amount){ t.MarkPermanentFailure(TransferStep.BalanceCheck,b.ErrorCode??"INSUFFICIENT_BALANCE"); await uow.SaveChangesAsync(ct); return;} t.MarkBalanceChecked(); await Next(new BalanceChecked(t.Id),ct);} }
public sealed class BalanceCheckedHandler(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow,IWalletProviderResolver resolver,IClock clock): StepHandlerBase(repo,outbox,uow), INotificationHandler<BalanceChecked>{ public async Task Handle(BalanceChecked n,CancellationToken ct){ var t=await Load(n.TransferId,ct); if(t is null||t.IsStepCompleted(TransferStep.Block)) return; var res=await resolver.Resolve(t.SourceProvider).BlockAsync(new(t.SourceWalletId,t.Amount,t.Currency,$"{t.Id}:BLOCK"),ct); if(!res.Success){ if(res.Retryable){ t.MarkRetryableFailure(TransferStep.Block,res.ErrorCode??"BLOCK_RETRY",clock.UtcNow.AddSeconds(10)); await uow.SaveChangesAsync(ct); return;} t.MarkPermanentFailure(TransferStep.Block,res.ErrorCode??"BLOCK_FAILED"); await uow.SaveChangesAsync(ct); return;} t.MarkAmountBlocked(res.BlockReferenceId!); await Next(new AmountBlocked(t.Id,res.BlockReferenceId!),ct);} }
public sealed class AmountBlockedHandler(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow,IWalletProviderResolver resolver,IClock clock): StepHandlerBase(repo,outbox,uow), INotificationHandler<AmountBlocked>{ public async Task Handle(AmountBlocked n,CancellationToken ct){ var t=await Load(n.TransferId,ct); if(t is null||t.IsStepCompleted(TransferStep.Transfer)) return; var r=await resolver.Resolve(t.DestinationProvider).TransferAsync(new(t.SourceWalletId,t.DestinationWalletId,t.Amount,t.Currency,$"{t.Id}:TRANSFER"),ct); if(!r.Success){ if(r.Retryable){ t.MarkRetryableFailure(TransferStep.Transfer,r.ErrorCode??"TRANSFER_RETRY",clock.UtcNow.AddSeconds(10)); await uow.SaveChangesAsync(ct); return;} t.MarkPermanentFailure(TransferStep.Transfer,r.ErrorCode??"TRANSFER_FAILED"); await outbox.AddAsync(new TransferFinalized(t.Id),ct); await uow.SaveChangesAsync(ct); return;} t.MarkMoneyTransferred(r.TransferReferenceId!); await Next(new MoneyTransferred(t.Id,r.TransferReferenceId!),ct);} }
public sealed class MoneyTransferredHandler(ITransferRepository repo,IOutboxRepository outbox,IUnitOfWork uow,IWalletProviderResolver resolver): StepHandlerBase(repo,outbox,uow), INotificationHandler<MoneyTransferred>{ public async Task Handle(MoneyTransferred n,CancellationToken ct){ var t=await Load(n.TransferId,ct); if(t is null) return; if(t.Status==TransferStatus.Failed && t.BlockReferenceId is not null){ await resolver.Resolve(t.SourceProvider).UnblockAsync(new(t.SourceWalletId,t.BlockReferenceId,$"{t.Id}:UNBLOCK"),ct); return;} if(t.IsStepCompleted(TransferStep.Finalize)) return; t.MarkFinalized(); t.MarkCompleted(); await Next(new TransferCompleted(t.Id),ct);} }
