using System.Text.Json;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using WalletTransfer.Application;
using WalletTransfer.Domain;

namespace WalletTransfer.Infrastructure;

public sealed class SystemClock : IClock { public DateTimeOffset UtcNow => DateTimeOffset.UtcNow; }
public sealed class WalletTransferDbContext(DbContextOptions<WalletTransferDbContext> options): DbContext(options){ public DbSet<Transfer> Transfers => Set<Transfer>(); public DbSet<OutboxRow> OutboxMessages=>Set<OutboxRow>(); protected override void OnModelCreating(ModelBuilder b){ b.Entity<Transfer>().HasKey(x=>x.Id); b.Entity<Transfer>().HasIndex(x=>x.ClientIdempotencyKey).IsUnique(); b.Entity<OutboxRow>().HasKey(x=>x.Id);} }
public sealed class OutboxRow{ public Guid Id{get;set;}=Guid.NewGuid(); public string Type{get;set;}=default!; public string Payload{get;set;}=default!; public DateTimeOffset OccurredAt{get;set;}=DateTimeOffset.UtcNow; public DateTimeOffset? ProcessedAt{get;set;} public int RetryCount{get;set;} public string? Error{get;set;} public string Status{get;set;}="Pending"; }
public sealed class TransferRepository(WalletTransferDbContext db): ITransferRepository { public Task AddAsync(Transfer transfer, CancellationToken ct)=>db.Transfers.AddAsync(transfer,ct).AsTask(); public Task<Transfer?> GetByClientKeyAsync(string key, CancellationToken ct)=>db.Transfers.FirstOrDefaultAsync(x=>x.ClientIdempotencyKey==key,ct); public Task<Transfer?> GetByIdAsync(Guid id, CancellationToken ct)=>db.Transfers.FirstOrDefaultAsync(x=>x.Id==id,ct); public Task<List<Transfer>> GetDueRetriesAsync(DateTimeOffset now, CancellationToken ct)=>db.Transfers.Where(x=>x.Status==TransferStatus.RetryPending&&x.RetryAt<=now).ToListAsync(ct); }
public sealed class OutboxRepository(WalletTransferDbContext db): IOutboxRepository { public Task AddAsync(object e, CancellationToken ct)=>db.OutboxMessages.AddAsync(new OutboxRow{Type=e.GetType().Name,Payload=JsonSerializer.Serialize(e,e.GetType())},ct).AsTask(); public async Task<List<OutboxMessage>> GetPendingAsync(int take,CancellationToken ct)=>await db.OutboxMessages.Where(x=>x.ProcessedAt==null).Take(take).Select(x=>new OutboxMessage(x.Id,x.Type,x.Payload,x.OccurredAt,x.ProcessedAt,x.RetryCount,x.Error,x.Status)).ToListAsync(ct); }
public sealed class EfUnitOfWork(WalletTransferDbContext db): IUnitOfWork { public Task<int> SaveChangesAsync(CancellationToken ct)=>db.SaveChangesAsync(ct); }
public sealed class WalletProviderResolver(IEnumerable<IWalletProvider> p): IWalletProviderResolver { public IWalletProvider Resolve(string name)=>p.First(x=>x.ProviderName.Equals(name,StringComparison.OrdinalIgnoreCase)); }
public abstract class FakeProviderBase(string name): IWalletProvider { protected readonly Dictionary<string,string> Idempotent=new(); public string ProviderName=>name; public Task<WalletValidationResult> ValidateWalletAsync(string walletId,string c,CancellationToken ct)=>Task.FromResult(walletId.Contains("invalid")?new(false,"INVALID_WALLET"):new(true)); public Task<BalanceResult> GetBalanceAsync(string walletId,string c,CancellationToken ct)=>Task.FromResult(walletId.Contains("low-balance")?new(false,0,"LOW_BALANCE"):new(true,100000)); public Task<ProviderTransferStatusResult> GetTransferStatusAsync(string id,CancellationToken ct)=>Task.FromResult(new ProviderTransferStatusResult("Done")); public Task<UnblockResult> UnblockAsync(UnblockMoneyRequest r,CancellationToken ct){ Idempotent[r.IdempotencyKey]="UNBLOCKED"; return Task.FromResult(new UnblockResult(true)); }
 public Task<BlockResult> BlockAsync(BlockMoneyRequest r,CancellationToken ct){ if(Idempotent.TryGetValue(r.IdempotencyKey,out var ex)) return Task.FromResult(new BlockResult(true,ex)); if(r.WalletId.Contains("retry-block")&&!Idempotent.ContainsKey(r.IdempotencyKey+":first")){Idempotent[r.IdempotencyKey+":first"]="1";return Task.FromResult(new BlockResult(false,null,"TEMP_BLOCK",true));} var refId=$"BLK-{Guid.NewGuid():N}"; Idempotent[r.IdempotencyKey]=refId; return Task.FromResult(new BlockResult(true,refId)); }
 public Task<TransferResult> TransferAsync(TransferMoneyRequest r,CancellationToken ct){ if(Idempotent.TryGetValue(r.IdempotencyKey,out var ex)) return Task.FromResult(new TransferResult(true,ex)); if(r.SourceWalletId.Contains("transfer-timeout")&&!Idempotent.ContainsKey(r.IdempotencyKey+":first")){Idempotent[r.IdempotencyKey+":first"]="1"; return Task.FromResult(new TransferResult(false,null,"TIMEOUT",true));} if(r.SourceWalletId.Contains("transfer-permanent-fail")) return Task.FromResult(new TransferResult(false,null,"PERM_FAIL",false)); var refId=$"TR-{Guid.NewGuid():N}"; Idempotent[r.IdempotencyKey]=refId; return Task.FromResult(new TransferResult(true,refId)); }
}
public sealed class InternalWalletProvider(): FakeProviderBase("Internal"); public sealed class ExternalWalletProvider(): FakeProviderBase("External");

public sealed class OutboxPublisherWorker(IServiceScopeFactory sf): BackgroundService { protected override async Task ExecuteAsync(CancellationToken stoppingToken){ while(!stoppingToken.IsCancellationRequested){ using var s=sf.CreateScope(); var db=s.ServiceProvider.GetRequiredService<WalletTransferDbContext>(); var mediator=s.ServiceProvider.GetRequiredService<IMediator>(); var rows=await db.OutboxMessages.Where(x=>x.ProcessedAt==null).Take(25).ToListAsync(stoppingToken); foreach(var row in rows){ try{ var evt=row.Type switch { nameof(TransferRequested)=>JsonSerializer.Deserialize<TransferRequested>(row.Payload), nameof(RequestValidated)=>JsonSerializer.Deserialize<RequestValidated>(row.Payload), nameof(WalletsValidated)=>JsonSerializer.Deserialize<WalletsValidated>(row.Payload), nameof(RulesChecked)=>JsonSerializer.Deserialize<RulesChecked>(row.Payload), nameof(BalanceChecked)=>JsonSerializer.Deserialize<BalanceChecked>(row.Payload), nameof(AmountBlocked)=>JsonSerializer.Deserialize<AmountBlocked>(row.Payload), nameof(MoneyTransferred)=>JsonSerializer.Deserialize<MoneyTransferred>(row.Payload), _=>null}; if(evt is not null) await mediator.Publish(evt,stoppingToken); row.ProcessedAt=DateTimeOffset.UtcNow; row.Status="Processed"; } catch(Exception ex){ row.RetryCount++; row.Error=ex.Message; } } await db.SaveChangesAsync(stoppingToken); await Task.Delay(500,stoppingToken);} } }
public sealed class RetryWorker(IServiceScopeFactory sf,IClock clock): BackgroundService { protected override async Task ExecuteAsync(CancellationToken stoppingToken){ while(!stoppingToken.IsCancellationRequested){ using var s=sf.CreateScope(); var repo=s.ServiceProvider.GetRequiredService<ITransferRepository>(); var outbox=s.ServiceProvider.GetRequiredService<IOutboxRepository>(); var uow=s.ServiceProvider.GetRequiredService<IUnitOfWork>(); var due=await repo.GetDueRetriesAsync(clock.UtcNow,stoppingToken); foreach(var t in due){ if(t.RetryCount>3) { t.MarkNeedManualReview("MAX_RETRIES"); continue; } await outbox.AddAsync(t.CurrentStep switch { TransferStep.Block=>new BalanceChecked(t.Id), TransferStep.Transfer=>new AmountBlocked(t.Id,t.BlockReferenceId!), _=>new TransferRequested(t.Id)},stoppingToken);} await uow.SaveChangesAsync(stoppingToken); await Task.Delay(1000,stoppingToken);} } }
public static class InfraDi { public static IServiceCollection AddInfrastructure(this IServiceCollection s,string conn="Data Source=wallet.db"){ s.AddDbContext<WalletTransferDbContext>(o=>o.UseSqlite(conn)); s.AddScoped<ITransferRepository,TransferRepository>(); s.AddScoped<IOutboxRepository,OutboxRepository>(); s.AddScoped<IUnitOfWork,EfUnitOfWork>(); s.AddSingleton<IClock,SystemClock>(); s.AddSingleton<IWalletProvider,InternalWalletProvider>(); s.AddSingleton<IWalletProvider,ExternalWalletProvider>(); s.AddSingleton<IWalletProviderResolver,WalletProviderResolver>(); s.AddHostedService<OutboxPublisherWorker>(); s.AddHostedService<RetryWorker>(); return s; } }
